In [1]:
pip install transformers # library from hugging face

In [3]:
from transformers import pipeline #flow of data from original system to destination

In [8]:
import transformers
print(transformers.__version__)

4.51.3


In [13]:
import librosa #python package for audio and music analysis
import torch #ml library
import IPython.display as display  #interactive command line for terminal
from transformers import Wav2Vec2ForCTC, Wav2Vec2Tokenizer  #[how find tune in speech recogniser, tokenizer]
import numpy as np #for arrays

In [15]:
tokenizer= Wav2Vec2Tokenizer.from_pretrained("facebook/wav2vec2-base-960h") #pretrined model is import
model= Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-base-960h")

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'Wav2Vec2CTCTokenizer'. 
The class this function is called from is 'Wav2Vec2Tokenizer'.
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/tokenization_wav2vec2.py:720: FutureWarning: The class `Wav2Vec2Tokenizer` is deprecated and will be removed in version 5 of Transformers. Please use `Wav2Vec2Processor` or `Wav2Vec2CTCTokenizer` instead.
  warnings.warn(


model.safetensors:   0%|          | 0.00/378M [00:00<?, ?B/s]

Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [23]:
audio, sampling_rate=librosa.load("v.mp3",sr=16000)

In [24]:
audio,sampling_rate

(array([0., 0., 0., ..., 0., 0., 0.], dtype=float32), 16000)

In [25]:
display.Audio("v.mp3",autoplay=True) #plays audio

In [38]:
input_values= tokenizer(audio,return_tensors='pt').input_values
input_values

tensor([[-0.0002, -0.0002, -0.0002,  ..., -0.0002, -0.0002, -0.0002]])

In [40]:
logits = model(input_values).logits #non normalized predictions
logits

tensor([[[ 15.2201, -27.9427, -27.6530,  ...,  -6.8967,  -7.1971,  -7.2959],
         [ 15.2355, -28.0205, -27.7293,  ...,  -6.9151,  -7.1696,  -7.3685],
         [ 15.2217, -28.0625, -27.7693,  ...,  -6.9100,  -7.1474,  -7.4479],
         ...,
         [ 15.6701, -27.9702, -27.6766,  ...,  -6.7658,  -7.5704,  -6.8585],
         [ 15.5768, -27.8930, -27.6015,  ...,  -6.7164,  -7.6119,  -6.8403],
         [ 15.4918, -27.7961, -27.5067,  ...,  -6.7873,  -7.6314,  -6.9094]]],
       grad_fn=<ViewBackward0>)

In [41]:
predicted_ids=torch.argmax(logits,dim=-1)

In [43]:
transcriptions=tokenizer.decode(predicted_ids[0])

In [46]:
transcriptions
#✨👏😊

'HAVE A NICE DAY'